apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  config.yaml: |
  JWT_KEY: jwt
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
stringData:
  config.yaml: |
  STRIPE_KEY: stripe-secret
