name: deploy-manifests

on: 
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod